server:
  port: 8080

database:
  dsn: ""

auth:
  enabled: true

upload:
  temp_dir: /tmp/gater
  max_file_size: 754974720

keepalive:
  enabled: true
  check_every: 1440
  visit_older: 30
  request_limit: 50
